version: '3.9'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - spotify_db_data:/var/lib/postgresql/data

volumes:
  spotify_db_data: